apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lab3
  name: mysql-pvc
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce